name: CI Checks

on:
    pull_request:
        branches: ['main']
    workflow_dispatch:

jobs:
    test-and-format:
        name: Test and Format
        runs-on: ubuntu-latest
        timeout-minutes: 20

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm

            - name: Install Dependencies
              run: npm ci

            - name: Run Strava Data Fetch
              run: npm run fetch-strava
              env:
                  STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
                  STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
                  STRAVA_REFRESH_TOKEN: ${{ secrets.STRAVA_REFRESH_TOKEN }}

            - name: Get Playwright version
              id: playwright-version
              run: echo "PLAYWRIGHT_VERSION=$(npm list @playwright/test | grep @playwright/test | cut -d'@' -f2)" >> $GITHUB_ENV

            - name: Cache Playwright browsers
              uses: actions/cache@v4
              id: playwright-cache
              with:
                  path: ~/.cache/ms-playwright
                  key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
                  restore-keys: |
                      ${{ runner.os }}-playwright-

            - name: Run Prettier Format Check
              run: npm run check:format

            - name: Run Unit Tests (Vitest)
              run: npm run test:unit

            - name: Install Playwright Browsers
              if: steps.playwright-cache.outputs.cache-hit != 'true'
              run: npx playwright install --with-deps

            - name: Run E2E Tests (Playwright)
              run: npm run test:e2e
